# Generated by Django 5.1.3 on 2024-11-26 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_domainmodel_user'),
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailermodel',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_mailers', to='domains.domainmodel'),
            preserve_default=False,
        ),
    ]
